name: Flask API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name:  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name:  Create .env file
        run: |
          echo "SECRET_KEY=example" >> .env
          echo "JWT_SECRET_KEY=example" >> .env
          echo "DATABASE_URL=sqlite:///test.db" >> .env
          echo "MAIL_SERVER=localhost" >> .env
          echo "MAIL_PORT=1025" >> .env
          echo "MAIL_USE_TLS=True" >> .env
          echo "MAIL_USERNAME=test" >> .env
          echo "MAIL_PASSWORD=test" >> .env
          echo "MAIL_DEFAULT_SENDER=test@example.com" >> .env
          echo "CLOUDINARY_CLOUD_NAME=demo" >> .env
          echo "CLOUDINARY_API_KEY=123456" >> .env
          echo "CLOUDINARY_API_SECRET=abc123" >> .env
          echo "STRIPE_SECRET_KEY=sk_test_dummy" >> .env
          echo "STRIPE_PUBLISHABLE_KEY=pk_test_dummy" >> .env

      - name: 🚦 Run tests (if any)
        run: |
          if ls tests/*.py test_*.py 1> /dev/null 2>&1; then
            echo "Tests found. Running pytest..."
            pytest
          else
            echo "⚠️ No tests found. Skipping pytest."
          fi
